version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - /app/node_modules
      - ${HOME}/.ssh:/root/.ssh
    environment:
      - NODE_ENV=development
    command: npm start
