services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspace
      - /workspace/app/node_modules
      - ${HOME}/.ssh:/root/.ssh
    environment:
      - NODE_ENV=development
    command: sleep infinity
